export const APPROVE_NEW_RETAILERS = 'APPROVE_NEW_RETAILERS';
export const APPROVE_NEW_RETAILERS_OFFSET = 'APPROVE_NEW_RETAILERS_OFFSET';
export const APPROVE_NEW_RETAILERS_ORDER = 'APPROVE_NEW_RETAILERS_ORDER';
export const APPROVE_NEW_RETAILERS_COUNT = 'APPROVE_NEW_RETAILERS_COUNT';
export const APPROVE_NEW_RETAILERS_ORDER_FIELD = 'APPROVE_NEW_RETAILERS_ORDER_FIELD';
export const APPROVE_NEW_RETAILERS_LOADING = 'APPROVE_NEW_RETAILERS_LOADING';
