export const APPROVED_RETAILERS = 'APPROVED_RETAILERS';
export const APPROVED_RETAILERS_OFFSET = 'APPROVED_RETAILERS_OFFSET';
export const APPROVED_RETAILERS_ORDER = 'APPROVED_RETAILERS_ORDER';
export const APPROVED_RETAILERS_COUNT = 'APPROVED_RETAILERS_COUNT';
export const APPROVED_RETAILERS_LOADING = 'APPROVED_RETAILERS_LOADING';
