export const REQUEST_AUTHENTICATED = 'REQUEST_AUTHENTICATED';
export const AUTHENTICATED = 'AUTHENTICATED_USER';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATED_ERROR = 'AUTHENTICATED_ERROR';