export const MANAGE_RETURNS = 'MANAGE_RETURNS';
export const MANAGE_RETURNS_COUNT = 'MANAGE_RETURNS_COUNT';
export const MANAGE_RETURNS_SORT = 'MANAGE_RETURNS_SORT';
export const MANAGE_RETURNS_OFFSET = 'MANAGE_RETURNS_OFFSET';
export const MANAGE_RETURNS_SEARCH = 'MANAGE_RETURNS_SEARCH';
export const SET_MANAGE_ORDER = 'SET_MANAGE_ORDER';
export const MANAGE_POST_RETURNS = 'MANAGE_POST_RETURNS';
export const MANAGE_RETURNS_LOADING = 'MANAGE_RETURNS_LOADING';