export const PRODUCTS = 'PRODUCTS';
export const PRODUCTS_OFFSET = 'PRODUCTS_OFFSET';
export const PRODUCTS_COUNT = 'PRODUCTS_COUNT';
export const PRODUCTS_FILTERS = 'PRODUCTS_FILTERS';
export const PRODUCTS_CURRENT_FILTER = 'PRODUCTS_CURRENT_FILTER';
export const PRODUCTS_RETAILERS = 'PRODUCTS_RETAILERS';
export const PRODUCTS_SEARCH = 'PRODUCTS_SEARCH';
export const PRODUCTS_CHECK = 'PRODUCTS_CHECK';
export const PRODUCTS_UNCHECK = 'PRODUCTS_UNCHECK';
export const PRODUCTS_CHECK_ALL = 'PRODUCTS_CHECK_ALL';
export const PRODUCTS_UNCHECK_ALL = 'PRODUCTS_UNCHECK_ALL';
export const PRODUCTS_ORDER = 'PRODUCTS_ORDER';
export const PRODUCTS_ORDER_FIELD = 'PRODUCTS_ORDER_FIELD';
export const RETAILERS_SEARCH_PRODUCTS = 'RETAILERS_SEARCH_PRODUCTS';
export const PRODUCTS_CHECK_RETAILER = 'PRODUCTS_CHECK_RETAILER';
export const PRODUCTS_UNCHECK_RETAILER = 'PRODUCTS_UNCHECK_RETAILER';
export const PRODUCTS_ALL = 'PRODUCTS_ALL';
export const PRODUCTS_CHECK_ALL_RETAILERS = 'PRODUCTS_CHECK_ALL_RETAILERS';
export const PRODUCTS_UNCHECK_ALL_RETAILERS = 'PRODUCTS_UNCHECK_ALL_RETAILERS';
export const PRODUCTS_PAGE = 'PRODUCTS_PAGE';
export const PRODUCTS_CHECK_ALL_ON_PAGE = 'PRODUCTS_CHECK_ALL_ON_PAGE';


