export const GET_BRANDS = 'GET_BRANDS';
export const LOADING_BY_SCROLL_BRANDS = 'LOADING_BY_SCROLL_BRANDS';
export const SET_FILTER_PRODUCTS_BRAND = 'SET_FILTER_PRODUCTS_BRAND';
export const SET_CURRENT_BRANDS = 'SET_CURRENT_BRANDS';