export const REPLENISH_PRODUCTS = 'REPLENISH_PRODUCTS';
export const REPLENISH_PRODUCTS_OFFSET = 'REPLENISH_PRODUCTS_OFFSET';
export const REPLENISH_PRODUCTS_ORDER = 'REPLENISH_PRODUCTS_ORDER';
export const REPLENISH_PRODUCTS_COUNT = 'REPLENISH_PRODUCTS_COUNT';
export const REPLENISH_PRODUCTS_FILTERS = 'REPLENISH_PRODUCTS_FILTERS';
export const REPLENISH_PRODUCTS_CURRENT_FILTER = 'REPLENISH_PRODUCTS_CURRENT_FILTER';
export const REPLENISH_PRODUCTS_SEARCH = 'REPLENISH_PRODUCTS_SEARCH';
export const REPLENISH_PRODUCTS_ORDER_FIELD = 'REPLENISH_PRODUCTS_ORDER_FIELD';
export const REPLENISH_PRODUCTS_CHECK = 'REPLENISH_PRODUCTS_CHECK';
export const REPLENISH_PRODUCTS_UNCHECK = 'REPLENISH_PRODUCTS_UNCHECK';
export const REPLENISH_PRODUCTS_CHECK_ALL = 'REPLENISH_PRODUCTS_CHECK_ALL';
export const REPLENISH_PRODUCTS_UNCHECK_ALL = 'REPLENISH_PRODUCTS_UNCHECK_ALL';
export const REPLENISH_BUY_PRODUCT = 'REPLENISH_BUY_PRODUCT';
export const RESET_MODAL_DATA = 'RESET_MODAL_DATA';
export const REPLENISH_PRODUCTS_LOADING = 'REPLENISH_PRODUCTS_LOADING';
export const REPLENISH_PRODUCTS_SUPPLIER_ID = 'REPLENISH_PRODUCTS_SUPPLIER_ID';
export const REPLENISH_PRODUCTS_BRANDS = 'REPLENISH_PRODUCTS_BRANDS';


