export const RETAILER_PRODUCTS = 'RETAILER_PRODUCTS';
export const RETAILER_PRODUCTS_OFFSET = 'RETAILER_PRODUCTS_OFFSET';
export const RETAILER_PRODUCTS_ORDER = 'RETAILER_PRODUCTS_ORDER';
export const RETAILER_PRODUCTS_COUNT = 'RETAILER_PRODUCTS_COUNT';
export const RETAILER_PRODUCTS_FILTERS = 'RETAILER_PRODUCTS_FILTERS';
export const RETAILER_PRODUCTS_CURRENT_FILTER = 'RETAILER_PRODUCTS_CURRENT_FILTER';
export const RETAILER_PRODUCTS_SEARCH = 'RETAILER_PRODUCTS_SEARCH';
export const RETAILER_PRODUCTS_ORDER_FIELD = 'RETAILER_PRODUCTS_ORDER_FIELD';
export const RETAILER_PRODUCTS_CHECK = 'RETAILER_PRODUCTS_CHECK';
export const RETAILER_PRODUCTS_UNCHECK = 'RETAILER_PRODUCTS_UNCHECK';
export const RETAILER_PRODUCTS_CHECK_ALL_ON_PAGE = 'RETAILER_PRODUCTS_CHECK_ALL_ON_PAGE';
export const RETAILER_PRODUCTS_CHECK_ALL = 'RETAILER_PRODUCTS_CHECK_ALL';
export const RETAILER_PRODUCTS_UNCHECK_ALL = 'RETAILER_PRODUCTS_UNCHECK_ALL';
export const RETAILER_PRODUCTS_APPROVE = 'RETAILER_PRODUCTS_APPROVE';
export const RETAILER_PRODUCTS_UNAPPROVE = 'RETAILER_PRODUCTS_UNAPPROVE';
export const RETAILER_PRODUCTS_DETAILS = 'RETAILER_PRODUCTS_DETAILS';
export const RETAILER_PRODUCTS_ADD_VARIANT = 'RETAILER_PRODUCTS_ADD_VARIANT';
export const RETAILER_PRODUCTS_REMOVE_VARIANT = 'RETAILER_PRODUCTS_REMOVE_VARIANT';
export const RETAILER_PRODUCTS_LOADING = 'RETAILER_PRODUCTS_LOADING';
export const RETAILER_PRODUCTS_ALL = 'RETAILER_PRODUCTS_ALL';
export const RETAILER_PRODUCTS_APPROVED = 'RETAILER_PRODUCTS_APPROVED';
export const RETAILER_PRODUCTS_MODAL_OPEN = 'RETAILER_PRODUCTS_MODAL_OPEN';
export const RETAILER_PRODUCTS_MODAL_CLOSE = 'RETAILER_PRODUCTS_MODAL_CLOSE';
export const RETAILER_PRODUCTS_PRODUCT = 'RETAILER_PRODUCTS_PRODUCT';





