export const CURRENT_RETAILER = 'CURRENT_RETAILER';
export const CURRENT_RETAILER_FILTERS = 'CURRENT_RETAILER_FILTERS';
export const CURRENT_RETAILER_PRODUCTS = 'CURRENT_RETAILER_PRODUCTS';
export const CURRENT_RETAILER_PRODUCTS_FILTERS = 'CURRENT_RETAILER_PRODUCTS_FILTERS';
export const CURRENT_RETAILER_LOADING = 'CURRENT_RETAILER_LOADING';

