export const ROLES = 'ROLES';
export const ROLES_CURRENT_ROLE = 'ROLES_CURRENT_ROLE';
export const ROLES_SUPPLIER_ID = 'ROLES_SUPPLIER_ID';
export const ROLES_RETAILER_ID = 'ROLES_RETAILER_ID';
export const ROLES_SUPPLIER_NAME = 'ROLES_SUPPLIER_NAME';
export const ROLES_RETAILER_NAME = 'ROLES_RETAILER_NAME';
